export interface Kir {
  id?: string;
  certificateNumber?: string;
  director?: string;
  directorLevel?: string;
  directorNip?: string;
  owner?: string;
  address?: string;
  registrationDate?: Date;
  registrationNumber?: string;
  chasisNumber?: string;
  engineNumber?: string;
  inspectionNumber?: string;
  frontPic?: string | File;
  backPic?: string | File;
  rightPic?: string | File;
  leftPic?: string | File;
  vehicleType?: string;
  vehicleBrand?: string;
  yearManufacture?: string;
  fuel?: string;
  engineCapacity?: string;
  enginePower?: string;
  tyreSize?: string;
  axleConfiguration?: string;
  curbWeight?: string;
  length?: string;
  width?: string;
  height?: string;
  front?: string;
  back?: string;
  sumbu1?: string;
  sumbu2?: string;
  sumbu3?: string;
  dimension?: string;
  jbbJbkb?: string;
  jbiJbki?: string;
  payload?: string;
  classPermit?: string;
  brake1?: string;
  brake2?: string;
  brake3?: string;
  brake4?: string;
  brake5?: string;
  headLamp1?: string;
  headLamp2?: string;
  headLamp3?: string;
  headLamp4?: string;
  inspectionResult?: string;
  expiryDate?: Date;
  inspector?: string;
  inspectorLevel?: string;
  inspectorNumber?: string;
  agency?: string;
  agencyLevel?: string;
  agencyNumber?: string;
  stamp1?: string;
  stamp2?: string;
  sign1?: string;
  sign2?: string;
  qr?: string;
  created?: Date;
  updated?: Date;
  deleted?: Date;
}
