import * as Yup from "yup";

export const addKirInitialValues: any = {
  owner: "",
  address: "",
  registrationDate: "",
  registrationNumber: "",
  chasisNumber: "",
  engineNumber: "",
  inspectionNumber: "",
  vehicleType: "",
  vehicleBrand: "",
  yearManufacture: "",
  fuel: "",
  engineCapacity: "",
  enginePower: "",
  tyreSize: "",
  axleConfiguration: "",
  curbWeight: "",
  length: "",
  width: "",
  height: "",
  front: "",
  back: "",
  sumbu1: "",
  sumbu2: "",
  sumbu3: "",
  dimension: "",
  jbbJbkb: "",
  jbiJbki: "",
  payload: "",
  classPermit: "",
  brake1: "",
  brake2: "",
  brake3: "",
  brake4: "",
  brake5: "",
  headLamp1: "",
  headLamp2: "",
  headLamp3: "",
  headLamp4: "",
  inspectionResult: "",
  frontPic: "",
  backPic: "",
  rightPic: "",
  leftPic: "",
  director: "",
  directorLevel: "",
  directorNumber: "",
  directorStamp: "",
  directorSignature: "",
  cardNumber: "",
  rfid: "",
  mst: "",
  coEmision: "",
  hcEmision: "",
  smokeDensity: "",
  inspector: "",
  inspectorLevel: "",
  inspectorNumber: "",
  inspectorStamp: "",
  inspectorSignature: "",
  region: "",
  origin: "",
  agency: "",
  agencyLevel: "",
  agencyNumber: "",
  agencyStamp: "",
  agencySignature: "",
};

export const addKirValidationSchema = Yup.object({
  owner: Yup.string().required("* Tidak boleh kosong"),
  address: Yup.string().required("* Tidak boleh kosong"),
  registrationDate: Yup.string().required("* Tidak boleh kosong"),
  registrationNumber: Yup.string().required("* Tidak boleh kosong"),
  chasisNumber: Yup.string().required("* Tidak boleh kosong"),
  engineNumber: Yup.string().required("* Tidak boleh kosong"),
  inspectionNumber: Yup.string().required("* Tidak boleh kosong"),
  vehicleType: Yup.string().required("* Tidak boleh kosong"),
  vehicleBrand: Yup.string().required("* Tidak boleh kosong"),
  yearManufacture: Yup.string().required("* Tidak boleh kosong"),
  fuel: Yup.string().required("* Tidak boleh kosong"),
  engineCapacity: Yup.string().required("* Tidak boleh kosong"),
  enginePower: Yup.string().required("* Tidak boleh kosong"),
  tyreSize: Yup.string().required("* Tidak boleh kosong"),
  axleConfiguration: Yup.string().required("* Tidak boleh kosong"),
  curbWeight: Yup.string().required("* Tidak boleh kosong"),
  length: Yup.string().required("* Tidak boleh kosong"),
  width: Yup.string().required("* Tidak boleh kosong"),
  height: Yup.string().required("* Tidak boleh kosong"),
  front: Yup.string().required("* Tidak boleh kosong"),
  back: Yup.string().required("* Tidak boleh kosong"),
  sumbu1: Yup.string().required("* Tidak boleh kosong"),
  sumbu2: Yup.string().required("* Tidak boleh kosong"),
  sumbu3: Yup.string().required("* Tidak boleh kosong"),
  dimension: Yup.string().required("* Tidak boleh kosong"),
  jbbJbkb: Yup.string().required("* Tidak boleh kosong"),
  jbiJbki: Yup.string().required("* Tidak boleh kosong"),
  payload: Yup.string().required("* Tidak boleh kosong"),
  classPermit: Yup.string().required("* Tidak boleh kosong"),
  brake1: Yup.string().required("* Tidak boleh kosong"),
  brake2: Yup.string().required("* Tidak boleh kosong"),
  brake3: Yup.string().required("* Tidak boleh kosong"),
  brake4: Yup.string().required("* Tidak boleh kosong"),
  brake5: Yup.string().required("* Tidak boleh kosong"),
  headLamp1: Yup.string().required("* Tidak boleh kosong"),
  headLamp2: Yup.string().required("* Tidak boleh kosong"),
  headLamp3: Yup.string().required("* Tidak boleh kosong"),
  headLamp4: Yup.string().required("* Tidak boleh kosong"),
  inspectionResult: Yup.string().required("* Pilih salah satu"),
  frontPic: Yup.mixed().required("* Diperlukan"),
  backPic: Yup.mixed().required("* Diperlukan"),
  rightPic: Yup.mixed().required("* Diperlukan"),
  leftPic: Yup.mixed().required("* Diperlukan"),
  director: Yup.string().required("* Tidak boleh kosong"),
  cardNumber: Yup.string().required("* Tidak boleh kosong"),
  rfid: Yup.string().required("* Tidak boleh kosong"),
  mst: Yup.string().required("* Tidak boleh kosong"),
  coEmision: Yup.string().required("* Tidak boleh kosong"),
  hcEmision: Yup.string().required("* Tidak boleh kosong"),
  smokeDensity: Yup.string().required("* Tidak boleh kosong"),
  inspector: Yup.string().required("* Tidak boleh kosong"),
  region: Yup.string().required("* Tidak boleh kosong"),
  origin: Yup.string().required("* Tidak boleh kosong"),
  agency: Yup.string().required("* Tidak boleh kosong"),
});

export const editKirInitialValues = { ...addKirInitialValues };

export const editKirValidationSchema = { ...addKirValidationSchema };
